# Generated by Django 4.2.26 on 2025-11-15 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('created', 'Criada'), ('running', 'Executando'), ('completed', 'Concluída'), ('error', 'Erro')], default='created', max_length=20)),
                ('urls', models.JSONField(default=list, help_text='URLs para scraping')),
                ('results', models.JSONField(default=list, help_text='Resultados do scraping')),
                ('screenshots', models.JSONField(default=list, help_text='Caminhos das screenshots')),
            ],
            options={
                'verbose_name': 'Sessão de Scraping',
                'verbose_name_plural': 'Sessões de Scraping',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('screenshot_path', models.CharField(blank=True, max_length=500)),
                ('data', models.JSONField(default=dict)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scraper.scrapingsession')),
            ],
            options={
                'verbose_name': 'Resultado de Scraping',
                'verbose_name_plural': 'Resultados de Scraping',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
