# Generated by Django 4.2.26 on 2025-11-15 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo do script', max_length=200)),
                ('code', models.TextField(help_text='Código Lua do script')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_executed_at', models.DateTimeField(blank=True, help_text='Última execução do script', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Script Lua',
                'verbose_name_plural': 'Scripts Lua',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScriptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Executando'), ('success', 'Sucesso'), ('error', 'Erro')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('request_args', models.JSONField(default=dict, help_text='Argumentos da requisição (URL, wait, etc.)')),
                ('response_data', models.JSONField(blank=True, help_text='Dados retornados pela execução', null=True)),
                ('logs', models.TextField(blank=True, help_text='Logs da execução')),
                ('screenshot_url', models.URLField(blank=True, help_text='URL da screenshot gerada', null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scraper.script')),
            ],
            options={
                'verbose_name': 'Execução de Script',
                'verbose_name_plural': 'Execuções de Scripts',
                'ordering': ['-started_at'],
            },
        ),
    ]
